### ISSUE TITLE
Check Ubuntu functionality

### ISSUE THREAD

**Issue by joelpt** [joelpt/sublimetext-print-to-html#2]
From the UserEcho printing thread:

Here's what the console spits out in Ubuntu 12.04 after ctrl+S then shift+alt+P:
Writing file /home/gordon/kinetic notes with encoding UTF-8
Plain text or no text, defaulting to: <pygments.lexers.TextLexer>
Traceback (most recent call last):
  File "/usr/lib/sublime-text-2/sublime_plugin.py", line 356, in run_
    return self.run(edit, **args)
  File "./PrintToHTML.py", line 72, in run
  File "./PrintToHTML.py", line 103, in send_to_browser
  File "./desktop/**init**.py", line 279, in open
  File "./desktop/**init**.py", line 86, in _run
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 1139, in _execute_child
OSError: [Errno 2] No such file or directory

My suspicion is that it's not finding the system browser properly.

**Comment by mmims** [comment]
Ubuntu does not have `gnome-open` installed by default. Use `xdg-open` or `sensible-browser` instead (see http://askubuntu.com/questions/8252/how-to-launch-default-web-browser-from-the-terminal)

**Comment by joelpt** [comment]
I believe mmims has fixed this one.
