### ISSUE TITLE
Problem to print php

### ISSUE THREAD

**Issue by Seraph11** [joelpt/sublimetext-print-to-html#4]
Hi first thanks for the plugin, it's excellent, but i've a problem when I want print a php code obtaining the follow exception:
Writing file application/config/database.php with encoding UTF-8
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./PrintToHTML.py", line 45, in run
  File "./PrintToHTML.py", line 192, in convert_to_html
  File "./PrintToHTML.py", line 146, in get_lexer
  File "./pygments/lexers/**init**.py", line 74, in get_lexer_by_name
  File "./pygments/lexer.py", line 470, in **call**
  File "./pygments/lexers/web.py", line 870, in **init**
ImportError: No module named _phpbuiltins

PD. Sorry for my bad english

**Comment by ghost** [comment]
This issue has been fixed in a similar plugin, SublimeHighlit. The author explains briefly how he achieved this on the comments.

https://github.com/n1k0/SublimeHighlight/issues/10
